### ISSUE TITLE
Cannot connect to skype account

### ISSUE THREAD

**Issue by tolacambo** [ShyykoSerhiy/phantom-skype#4]
Hello,
I got only the first log "a user connected" and nothing else is happened.
Could you provide more detail about how to connect to Skype?

**Comment by ShyykoSerhiy** [comment]
Make sure that you Skype account is connected to Microsoft account. You can check if your accounts are connected if try to login into OneDrive
![issuez](https://cloud.githubusercontent.com/assets/1106995/9310438/6c1360fe-4518-11e5-9f8f-ede9eb8346e8.gif).
Then try to run demo with

```
node nodeDemo.js yourmicrosoftaccount@something.com password
```

**Comment by ShyykoSerhiy** [comment]
There was error(because of a change from Microsoft) which is fixed in 0.1.1

**Comment by tolacambo** [comment]
line 137: page.open('https://login.live.com/') returns fail.

page.open('https://login.live.com/', function (status) {
 console.log(status);
});

Could you check it if it works on your PC. I am using CentOS 6.6.

**Comment by ShyykoSerhiy** [comment]
Simple code as this:

```
var page = require('webpage').create();
page.open('https://login.live.com/', function (status) {
  console.log(status);
});
```

prints success in console if i run it with

```
phantomjs test.js
```

. 
Can you try to use for example

```
page.open('https://google.com/', function (status) {
  console.log(status);
});
```

to make sure, that you phantomjs installation is ok?

**Comment by tolacambo** [comment]
the phantomjs is working. However, It cannot open https site because of --ssl-protocol. If we can update '--ssl-protocol':'tlsv1' somewhere in the code, it will work.

**Comment by tolacambo** [comment]
I got it work now because of Phantom version. I need to install the latest version.

Thank you so much.

**Comment by ShyykoSerhiy** [comment]
Great! Closing the issue.
